from __future__ import annotations

from pathlib import Path

from libs.autoloop.state import (
    BrainstormItem,
    IterationRecord,
    State,
    atomic_write_text,
)

_TITLE_MAX = 60


def _fmt_source(item: BrainstormItem) -> str:
    if item.source.finding_id:
        return f"{item.source.kind}:{item.source.finding_id}"
    return item.source.kind


def _fmt_lift(item: BrainstormItem, lift_index: dict[str, float | None]) -> str:
    lift = lift_index.get(item.id)
    if lift is None:
        return "—"
    return f"+{lift:.3f}" if lift >= 0 else f"{lift:.3f}"


def _build_lift_index(iterations: list[IterationRecord]) -> dict[str, float | None]:
    index: dict[str, float | None] = {}
    for rec in iterations:
        if rec.executor and rec.executor.brainstorm_id:
            bid = rec.executor.brainstorm_id
            index[bid] = rec.executor.lift
    return index


def _truncate(title: str, max_len: int = _TITLE_MAX) -> str:
    if len(title) <= max_len:
        return title
    return title[: max_len - 1] + "…"


def _status_counts(items: list[BrainstormItem]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for item in items:
        counts[item.status] = counts.get(item.status, 0) + 1
    return counts


def rebuild_registry(state: State) -> Path:
    items = state.load_brainstorm()
    iterations = state.recent_iterations(n=200)

    items_sorted = sorted(items, key=lambda i: (-i.tier_score, i.id))
    lift_index = _build_lift_index(iterations)
    counts = _status_counts(items)

    total = len(items)
    queued = counts.get("queued", 0)
    run_completed = counts.get("run_completed", 0)
    run_failed = counts.get("run_failed", 0)
    deduped_rejected = counts.get("deduped_rejected", 0)

    header = (
        "# Brainstorm Idea Registry\n\n"
        "_Generated by autoloop supervisor — DO NOT EDIT (regenerated each planner phase)._\n\n"
        f"Total ideas: {total} · queued: {queued} · run_completed: {run_completed}"
        f" · run_failed: {run_failed} · deduped_rejected: {deduped_rejected}\n\n"
        "| Tier | Score | Status | Title | Source | Run | Lift |\n"
        "|---|---|---|---|---|---|---|\n"
    )

    rows: list[str] = []
    for item in items_sorted:
        tier = item.tier
        score = f"{item.tier_score:.2f}"
        status = item.status
        title = _truncate(item.title)
        source = _fmt_source(item)
        run = item.run_id or "—"
        lift = _fmt_lift(item, lift_index)
        rows.append(f"| {tier} | {score} | {status} | {title} | {source} | {run} | {lift} |")

    content = header + "\n".join(rows) + ("\n" if rows else "")

    out_path = state.state_dir / "idea_registry.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    atomic_write_text(out_path, content)
    return out_path
